# POST http://localhost:3000/signin 
# Content-Type: application/json

# {
#     "email": "madhawath@gmail.com",
#     "password": "Madhawa123"
# },

POST http://localhost:3000/signup 
Content-Type: application/json

{
    "fullName": "Mad",
    "email": "madhawath@gmail.com",
    "password" : "Madhawa123"
}